# Generated by Django 4.0.3 on 2022-04-04 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorium', '0003_alter_category_options_memory_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='body',
            new_name='description',
        ),
    ]
